### ISSUE TITLE
No socket close notifications in certain circumstances

### ISSUE THREAD

**Issue by sebakerckhof** [faye/faye-websocket-node#56] opened 2016-06-01 08:44 UTC
Okay, related to: https://github.com/faye/faye-websocket-node/issues/54

I notice I do not get close notifications when I unplug my network cable

eg:

``` js
'use strict';
var WebSocket = require("faye-websocket");
var url = "ws://10.196.46.53:80/websocket";
var socket = new WebSocket.Client(url, null);
socket.on("end", function() { console.log("END");});
socket.on("error", function(error) {console.log("ERROR",error.message);});
socket.on("close", function(event) {console.log("CLOSE",event.code,event.reason);});

setTimeout(()=>{socket.close();},10000);
```

If I run this, I get a `close` notification after 10 seconds. If I unplug my network cable within the 10 seconds of the timeout, I do not get any close or error notification when the timeout is triggered and calls socket.close();

If I try to do something equivalent with raw sockets, I get:

``` js
var net    = require('net');
var netOptions = {
    host: '10.196.46.53',
    port: '80'
};
var socket = net.connect(netOptions);
socket.on('error',(err) => {console.log("ERR",err);});
socket.on('close',(err) => {console.log("CLOSE",err);});

setTimeout(()=>{socket.destroy();},10000);
```

**Comment by jcoglan** [comment] 2016-06-01 08:53
Can you be more specific what you mean by 'network cable'? Is it, say, an ethernet plugged into a laptop, or the input to your wifi router, or something else? Can you reproduce this bug by turning wifi off?

Just asking because none of my computers I have available use wired networking.

**Comment by sebakerckhof** [comment] 2016-06-01 09:14
Thanks for the fast reply, I did some more testing.
My setup is like:
PC running client - Switch - Pc running server

The PC running the client runs Debian wheezy and is connected through an ethernet cable to the switch. It doesn't have wifi.
If I unplug the ethernet cable, I never get the `close` notification when I call `close()` (never = I waited 5 minutes).

I just did the same thing on my windows 7 laptop that has both wired and wireless networking. There the behavior is different. I do get a `close` notification, but only about 10 seconds after I call `close()`. Behavior for disabling the wifi seems to be the same as for unplugging the network cable.

So it seems the `close()` functions is waiting on something. On windows it takes a couple of seconds, on linux it hangs forever.

If instead of `socket.close()` I call `socket._stream.destroy()`. I do get a notification immediately on both platforms.

**Comment by jcoglan** [comment] 2016-06-10 19:48
I'm not able to easily reproduce this with the systems I have available at the moment. To detect the network connection being broken, this module relies on events emitted by the `_stream` object. Are you able to find out what events if any it emits when you unplug the cable?

**Comment by ivan** [comment] 2016-07-04 22:30
Windows and Linux behave very differently when you unplug the Ethernet cable.  Linux doesn't break your TCP connections (patiently waiting for you to plug the cable back in), while Windows for some reason invalidates existing TCP connections.

**Comment by jcoglan** [comment] 2016-07-05 08:16
Thank you, @ivan. This would explain the TCP socket not emitting `end`, `close` or `error` in this situation. @sebakerckhof does a browser `WebSocket` remain in the open state when you disconnect the ethernet?

**Comment by jcoglan** [comment] 2016-10-11 20:03
@sebakerckhof Did you see my last question? Do you have any more information on this issue?

**Comment by sebakerckhof** [comment] 2016-10-11 20:05
Yeah, I've been working on different projects and kind of lost this out of my sight. I'll test it tomorrow when I have my dual-boot machine on hands.

**Comment by jcoglan** [comment] 2017-04-12 19:20
@sebakerckhof Has there been any progress on this, or should I close the issue?

**Comment by jcoglan** [comment] 2019-05-29 13:34
I'm going to close this issue as there's been no feedback on my last question, but please re-open it if you have further information.

**Closed by jcoglan** 2019-05-29 13:34 UTC
